# Tên của workflow
name: Generate Snake Animation

# Controls when the action will run
on:
  # Lên lịch chạy tự động mỗi ngày vào lúc 0 giờ (UTC)
  schedule:
    - cron: "0 0 * * *"

  # Cho phép bạn chạy workflow này thủ công từ tab Actions
  workflow_dispatch:

# Một workflow bao gồm một hoặc nhiều job
jobs:
  # Job này có tên là "build"
  build:
    # Chạy trên phiên bản Ubuntu mới nhất
    runs-on: ubuntu-latest

    steps:
      # Kiểm tra (checkout) code trong repository của bạn
      - uses: actions/checkout@v3

      # Bước chính: Sử dụng Action để tạo ảnh con rắn
      - uses: Platane/snk@v3
        with:
          # Tên người dùng GitHub của bạn (bắt buộc)
          # Thay 'your-github-username' bằng tên user của bạn
          github_user_name: your-github-username

          # Các file output sẽ được tạo ra
          # Bạn có thể tùy chỉnh màu sắc và định dạng ở đây
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
